# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a1af3383684d15cbcabd6964aea78b62ffa237c0daa185dcfeab0581dca7c819716d2a2033c16051acf02dbb55ce6d1215e5cd0bd3b418db3e0c736a530023

test:
  secret_key_base: 1a535967a8570eb772575ee854992f1736ee69ddb8a209c5594f4b01e649b651df21ec0a12430759ed2df6efa30c244e56b92e52a1d5dfa8cf0ecb4faa60e486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
